Updated Server Files

diff --git a/17.0/Dockerfile b/17.0/Dockerfile
--- a/17.0/Dockerfile
+++ b/17.0/Dockerfile
@@ -1,5 +1,6 @@
 # Use Ubuntu base image
 FROM ubuntu:jammy
+MAINTAINER Odoo S.A. <info@odoo.com>
 
 SHELL ["/bin/bash", "-xo", "pipefail", "-c"]
 
@@ -9,7 +10,7 @@ ENV LANG en_US.UTF-8
 # Retrieve the target architecture to install the correct wkhtmltopdf package
 ARG TARGETARCH
 
-# Install dependencies including Nginx and PostgreSQL client, maintain existing dependencies
+# Install dependencies, including Nginx and PostgreSQL client
 RUN apt-get update && \
     DEBIAN_FRONTEND=noninteractive \
     apt-get install -y --no-install-recommends \
@@ -21,6 +22,7 @@ RUN apt-get update && \
         libssl-dev \
         node-less \
         npm \
+        nginx \
         python3-magic \
         python3-num2words \
         python3-odf \
@@ -37,63 +39,89 @@ RUN apt-get update && \
         python3-xlrd \
         python3-xlwt \
         xz-utils \
-        nginx \
-        postgresql-client \
-        && rm -rf /var/lib/apt/lists/*
-
-# Install wkhtmltopdf based on target architecture
-RUN if [ -z "${TARGETARCH}" ]; then \
+        fontconfig \
+        libxext6 \
+        libxrender1 \
+        xfonts-75dpi \
+        xfonts-base \
+    && if [ -z "${TARGETARCH}" ]; then \
         TARGETARCH="$(dpkg --print-architecture)"; \
     fi; \
     WKHTMLTOPDF_ARCH=${TARGETARCH} && \
     case ${TARGETARCH} in \
     "amd64") WKHTMLTOPDF_ARCH=amd64 && WKHTMLTOPDF_SHA=967390a759707337b46d1c02452e2bb6b2dc6d59  ;; \
     "arm64")  WKHTMLTOPDF_SHA=90f6e69896d51ef77339d3f3a20f8582bdf496cc  ;; \
+    "ppc64le" | "ppc64el") WKHTMLTOPDF_ARCH=ppc64el && WKHTMLTOPDF_SHA=5312d7d34a25b321282929df82e3574319aed25c  ;; \
     esac \
     && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_${WKHTMLTOPDF_ARCH}.deb \
     && echo ${WKHTMLTOPDF_SHA} wkhtmltox.deb | sha1sum -c - \
     && apt-get install -y --no-install-recommends ./wkhtmltox.deb \
     && rm -rf /var/lib/apt/lists/* wkhtmltox.deb
 
+# Install latest postgresql-client
+RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
+    && GNUPGHOME="$(mktemp -d)" \
+    && export GNUPGHOME \
+    && repokey='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' \
+    && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
+    && gpg --batch --armor --export "${repokey}" > /etc/apt/trusted.gpg.d/pgdg.gpg.asc \
+    && gpgconf --kill all \
+    && rm -rf "$GNUPGHOME" \
+    && apt-get update  \
+    && apt-get install --no-install-recommends -y postgresql-client \
+    && rm -f /etc/apt/sources.list.d/pgdg.list \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install rtlcss (on Debian buster)
+RUN npm install -g rtlcss
+
 # Install Odoo
 ENV ODOO_VERSION 17.0
-ARG ODOO_RELEASE=20240904
-ARG ODOO_SHA=9fd807d55facb850ead1ad86dc628e26961dfb20
+ARG ODOO_RELEASE=20240826
+ARG ODOO_SHA=7f40f642e89d8ecd43d748c23dc4251fcdca84ca
 RUN curl -o odoo.deb -sSL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb \
     && echo "${ODOO_SHA} odoo.deb" | sha1sum -c - \
     && apt-get update \
     && apt-get -y install --no-install-recommends ./odoo.deb \
     && rm -rf /var/lib/apt/lists/* odoo.deb
 
+# Create a new directory for custom modules and copy the modules there
+RUN mkdir -p /mnt/custom-modules
+COPY ./custom-modules /mnt/custom-modules
+
+# Ensure permissions are correct for the custom modules
+RUN chown -R odoo /mnt/custom-modules
+
 # Copy entrypoint script and Odoo configuration file
 COPY ./entrypoint.sh /
 COPY ./odoo.conf /etc/odoo/
 
-# Nginx configuration
+# Configure Nginx
 COPY ./nginx.conf /etc/nginx/nginx.conf
-
-# Replace the server name in Nginx with an environment variable
 RUN envsubst '${SERVER_NAME}' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf.tmp && mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf
 
-# Set permissions and Mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
+# Start Nginx and check configuration
+RUN service nginx start || (echo "Nginx failed to start" && cat /var/log/nginx/error.log)
+
+# Set permissions and mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
 RUN chown odoo /etc/odoo/odoo.conf \
     && mkdir -p /mnt/extra-addons \
     && chown -R odoo /mnt/extra-addons
 VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]
 
-# Expose Odoo and Nginx services
+# Ensure that the custom modules directory is in the addons path
+RUN echo "\naddons_path = /mnt/custom-modules,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons" >> /etc/odoo/odoo.conf
+
+# Expose necessary ports
 EXPOSE 80 8069 8072
 
 # Set the default config file
 ENV ODOO_RC /etc/odoo/odoo.conf
 
-# Copy wait-for-psql script and set permissions
 COPY wait-for-psql.py /usr/local/bin/wait-for-psql.py
-RUN chmod +x /usr/local/bin/wait-for-psql.py
 
 # Set default user when running the container
 USER odoo
 
-# Entrypoint script to handle Odoo and Nginx services
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["odoo"]
